services:
  rabbitmq:
    image: todomvc_rabbitmq
    container_name: todomvc_rabbitmq
    build:
      context: ./services/rabbitmq
      dockerfile: Dockerfile
    volumes:
      - todomvc-rabbitmq-data:/var/lib/rabbitmq
    networks:
        - backnet
    env_file:
    - .env.secrets
    - ${APP_ENV}.env
    ports:
    - "5672:5672"
    expose:
    - "5672"
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        timeout: 20s
        retries: 10

  postgres:
    image: todomvc_postgres
    platform: linux/amd64
    container_name: todomvc_postgres
    build:
      context: ./services/postgres
      dockerfile: Dockerfile
    restart: always
    networks:
      - backnet
    env_file:
      - .env.secrets
      - ${APP_ENV}.env
    volumes:
        - todomvc-postgres-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
        timeout: 20s
        retries: 10
    expose:
        - 5432
    user: postgres

  api:
    restart: always
    image: todomvc_api
    container_name: todomvc_api
    build:
        context: .
        dockerfile: ./flask/Dockerfile
    volumes:
      - ./flask:/api
      - ./common:/api/common
    ports:
      - '5000:5000'
    env_file:
      - .env.secrets
      - ${APP_ENV}.env
    depends_on:
      postgres:
          condition: service_healthy
      rabbitmq:
          condition: service_healthy
    networks:
      - backnet

  email_transmitter:
    image: ecorrouge/email-transmitter:latest
    container_name: todomvc_email_transmitter
    restart: unless-stopped
    networks:
      - backnet
    env_file:
      - ./.env.secrets
      - ./${APP_ENV}.env
    environment:
      - MESSAGING_TYPE=RabbitMqConnection
      - PROCESSOR_TYPE=EmailServiceProcessor
      - PROCESSOR_MODULE=services.email_transmitter.src.email_processor
      - CONFIG_FILEPATH=/app/src/services/email_transmitter/src/config.json
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./services/email_transmitter/config.json:/app/src/services/email_transmitter/src/config.json


volumes:
  todomvc-postgres-data:
    name: todomvc-postgres-data
  todomvc-rabbitmq-data:
    name: todomvc-rabbitmq-data
    driver: local

networks:
  backnet:
